### ISSUE TITLE
crispRVariants Sticker not rendered using master

### ISSUE THREAD

**Issue by schmeing** [robinsonlabuzh/robinsonlabuzh.github.io#17]
"stickers/crispRVariants.png" is called in tools.Rmd, while "stickers/CrispRVariants.png" is the existing file.
I don't know why the html on the page is rendered correctly, but still should be fixed in case somebody wants to modify tools page later.

**Comment by markrobinsonuzh** [comment]
Fixed in this commit: https://github.com/robinsonlabuzh/robinsonlabuzh.github.io/commit/a680f72b6ce10bb7325d01fc24dfb1a481052e01
