### ISSUE TITLE
Add descriptions to README

### ISSUE THREAD

**Issue by csoneson** [robinsonlabuzh/robinsonlabuzh.github.io#36]
The following descriptions are missing from the README (empty sections):
- [ ] Adding members (including where to put the picture and to reduce the size)
- [ ] Adding news item (which news items should be added, by whom, and how)

We could also move these instructions to the Wiki.

**Comment by markrobinsonuzh** [comment]
I added a new branch (https://github.com/robinsonlabuzh/robinsonlabuzh.github.io/tree/new_bits_to_readme) with some comments on news item.

@imallona could you add a few sentences about how to run your image compressor and where to stick image files?

**Comment by imallona** [comment]
Hi, just added the image compression tips; changes have been merged into the new_bits_to_readme branch.
