### ISSUE TITLE
re-org of 'people' page

### ISSUE THREAD

**Issue by markrobinsonuzh** [robinsonlabuzh/robinsonlabuzh.github.io#4]
- get content out of yaml and just straight in Rmd
- re-org format to make everything look good
- chase people to get their pictures uploaded

**Comment by csoneson** [comment]
Also, once the formatting is done:
[ ] update README with instructions on how to add new members
[ ] add list of alumni

**Comment by lmweber** [comment]
Replaced code using `knitr` and `kableExtra` in RMarkdown, instead of `members.yml` file. See additional comments in pull request #7 (merged).

**Comment by lmweber** [comment]
I also rearranged the order by seniority (I think, although I may have slightly mixed it up), and formatted it all nicely (linebreaks were difficult!)

**Comment by markrobinsonuzh** [comment]
I consider the "re-org" done, but still need people (including myself) to update content.
