### ISSUE TITLE
nice pictures for base page (+ nice figures for research page)

### ISSUE THREAD

**Issue by markrobinsonuzh** [robinsonlabuzh/robinsonlabuzh.github.io#6]
- if anyone has nice pictures of UZH campus or cool looking figures, discuss with Mark and/or the rest and we'll select a few to commit and add to either the landing page or the research page

**Comment by lmweber** [comment]
I took a few photos of the campus yesterday afternoon. I have saved them on Dropbox in 'Pics/campus_photos'. One of these could work for the landing page. Alternatively, we could use something "Swiss" like a picture of mountains or Zurich.

**Comment by markrobinsonuzh** [comment]
Added one of the pictures to the landing page: https://github.com/robinsonlabuzh/robinsonlabuzh.github.io/commit/cd75569757c37cf4c5b9ddc643fc9bd0ffa7af50
